#!/usr/bin/env bash

VIM_PLUGINS="
tpope/vim-fugitive
elzr/vim-json
fatih/vim-go
avakhov/vim-yaml
leafgarland/typescript-vim
editorconfig/editorconfig-vim
lifepillar/vim-solarized8
Shougo/vimproc.vim
vim-js-pretty-template
hashivim/vim-terraform
valloric/youcompleteme
Quramy/tsuquyomi
scrooloose/nerdtree
scrooloose/nerdcommenter
"

if ! $(dpkg -s vim &> /dev/null); then
    sudo DEBIAN_FRONTEND=noninteractive apt-get install --qq -y vim 
fi

for plugin in $VIM_PLUGINS; do
  plugin_name="${plugin##*/}"

  echo
  if [ ! -d $HOME/.vim/bundle/$plugin_name ]; then
    echo "VIM-PLUGINS: $plugin not found. Installing"
    git clone --recurse-submodules --depth=1 "https://github.com/$plugin" "$HOME/.vim/bundle/$plugin_name"
  else
    echo "VIM-PLUGINS: $plugin found. Checking for updates"
    cd "$HOME/.vim/bundle/$plugin_name" && git pull
  fi
done
