#!/usr/bin/env bash

VIM_PLUGINS="
tpope/vim-fugitive
elzr/vim-json
ctrlpvim/ctrlp.vim
fatih/vim-go
vim-airline/vim-airline
vim-airline/vim-airline-themes
elzr/vim-json
airblade/vim-gitgutter
avakhov/vim-yaml
leafgarland/typescript-vim
editorconfig/editorconfig-vim
lifepillar/vim-solarized8
hashivim/vim-terraform
Quramy/tsuquyomi
scrooloose/nerdtree
scrooloose/nerdcommenter
Xuyuanp/nerdtree-git-plugin
plasticboy/vim-markdown
iamcco/markdown-preview.vim
ledger/vim-ledger
"

mkdir -p ~/.vim/autoload ~/.vim/bundle
# make sure we have pathogen
if [ ! -e ~/.vim/autoload/pathogen.vim ]; then
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
fi

for plugin in $VIM_PLUGINS; do
  plugin_name="${plugin##*/}"

  if [ ! -d $HOME/.vim/bundle/$plugin_name ]; then
    echo "VIM-PLUGINS: $plugin not found. Installing"
    git clone --recurse-submodules --depth=1 "https://github.com/$plugin" "$HOME/.vim/bundle/$plugin_name"
  else
    echo "VIM-PLUGINS: $plugin found. Checking for updates"
    cd "$HOME/.vim/bundle/$plugin_name" && git pull
  fi
done
